//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.AppBanwao.TariffBazaar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int RentItemId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string TermsConditions { get; set; }
        public Nullable<int> MinimumDays { get; set; }
        public Nullable<decimal> SecurityAmount { get; set; }
        public Nullable<decimal> Rent { get; set; }
        public Nullable<int> RentCriteria { get; set; }
        public string ImageLink1 { get; set; }
        public string ImageLink2 { get; set; }
        public string ImageLink3 { get; set; }
        public Nullable<bool> Shipable { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> ForRent { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
    }
}
