//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.AppBanwao.TariffBazaar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpHolder
    {
        public int OtpId { get; set; }
        public string OtpReference { get; set; }
        public string Otp { get; set; }
    }
}
